//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVANT_Scada.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class action_log
    {
        public int idaction_log { get; set; }
        public string Name { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
