//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVANT_Scada.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ion_sp
    {
        public string name { get; set; }
        public int DB { get; set; }
        public int DBB { get; set; }
        public Nullable<double> Anod_I_SP { get; set; }
        public Nullable<double> Anod_U_SP { get; set; }
        public Nullable<double> Anod_P_SP { get; set; }
        public Nullable<double> Heat_I_SP { get; set; }
        public Nullable<double> Heat_U_SP { get; set; }
        public Nullable<double> Heat_P_SP { get; set; }
    }
}
