//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVANT_Scada.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ion_read
    {
        public Nullable<double> Anod_I { get; set; }
        public Nullable<double> Anod_U { get; set; }
        public Nullable<double> Anod_P { get; set; }
        public Nullable<double> Heat_I { get; set; }
        public Nullable<double> Heat_U { get; set; }
        public Nullable<double> Heat_P { get; set; }
        public Nullable<bool> Auto_mode { get; set; }
        public Nullable<bool> Power_on { get; set; }
        public Nullable<bool> Turn_On { get; set; }
        public Nullable<bool> Interlock { get; set; }
        public Nullable<bool> Failure { get; set; }
        public Nullable<bool> Power_Failure { get; set; }
        public Nullable<bool> Temperature_Failure { get; set; }
        public Nullable<bool> Repeat_Failure { get; set; }
        public Nullable<bool> Filament_Failure { get; set; }
        public Nullable<bool> Turn_Off { get; set; }
        public Nullable<bool> Emergency_Stop { get; set; }
        public Nullable<bool> Power_Stop { get; set; }
        public Nullable<bool> Temperature_Stop { get; set; }
        public Nullable<bool> Other_Failure { get; set; }
        public string name { get; set; }
        public int DB { get; set; }
        public int DBB { get; set; }
    }
}
