//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVANT_Scada.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Real_Tag_Entitys : DbContext
    {
        public Real_Tag_Entitys()
            : base("name=Real_Tag_Entitys")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<real> real { get; set; }
        public virtual DbSet<valves> valves { get; set; }
        public virtual DbSet<command_bit> command_bit { get; set; }
        public virtual DbSet<crio> crio { get; set; }
        public virtual DbSet<fvp> fvp { get; set; }
        public virtual DbSet<process> process { get; set; }
        public virtual DbSet<valve_log> valve_log { get; set; }
        public virtual DbSet<ion_read> ion_read { get; set; }
        public virtual DbSet<ion_sp> ion_sp { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<real_log> real_log { get; set; }
        public virtual DbSet<crio_log> crio_log { get; set; }
        public virtual DbSet<fvp_log> fvp_log { get; set; }
        public virtual DbSet<action_log> action_log { get; set; }
    }
}
