//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVANT_Scada.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Real_Tag_Entitys : DbContext
    {
        public Real_Tag_Entitys()
            : base("name=Real_Tag_Entitys")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<real> real { get; set; }
        public virtual DbSet<valves> valves { get; set; }
        public virtual DbSet<command_bit> command_bit { get; set; }
    }
}
