//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVANT_Scada.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class valve_log
    {
        public string name { get; set; }
        public Nullable<bool> opened { get; set; }
        public Nullable<bool> closed { get; set; }
        public Nullable<bool> block { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
        public int valve_logcol { get; set; }
    }
}
